--
-- File generated with SQLiteStudio v3.3.3 on бс шўы 16 15:57:28 2022
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: Service
CREATE TABLE Service (IdService INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ServiceName VARCHAR NOT NULL UNIQUE, DurationMin INTEGER NOT NULL DEFAULT (0), Price DECIMAL (10, 2) NOT NULL);

-- Table: ServiceUser
CREATE TABLE ServiceUser (Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, IdService INTEGER NOT NULL, IdUser INTEGER NOT NULL, DateStart DATETIME NOT NULL, DateEnd DATETIME NOT NULL, TotalCoast DECIMAL (10, 2) NOT NULL);

-- Table: User
CREATE TABLE User (Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Phone VARCHAR (15) UNIQUE NOT NULL, Email VARCHAR UNIQUE NOT NULL, IdChat INTEGER UNIQUE NOT NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
